!
hostname br-whitefield
!
interface lo
 ip address 10.255.0.4/32
!
interface eth1
 ip address 10.1.3.2/30
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.4
 network 10.1.3.0/30 area 0
 network 10.255.0.4/32 area 0
!
router bgp 65001
 bgp router-id 10.255.0.4
 neighbor 10.255.0.1 remote-as 65001
 neighbor 10.255.0.1 update-source lo
 !
 address-family ipv4 unicast
  network 10.3.0.0/24
 exit-address-family
!
ip route 10.3.0.0/24 lo
!
line vty
!
